### ISSUE TITLE
"getParameterOrder" not available for .Call() for package ....

### ISSUE THREAD

**Issue by Craig44** [mlysy/RcppTMBTest#4]
Not an issue but I think useful for future users.
If you re-run documentation builders i.e. `devtools::document()` they will remove the 
`useDynLib({MyTMBPackage}, .registration=TRUE); useDynLib({MyTMBPackage}_TMBExports)` section in the `NAMESPACE ` file.
You will get the error stated in the subject line. Just add the `useDynLib` back to resolve the issue.

**Comment by mlysy** [comment]
Can you please clarify when this happens?  It should not if you run the command on the **TMBtools** repo, because the line
```
#' @rawNamespace useDynLib(TMBtools, .registration = TRUE); useDynLib(TMBtools_TMBExports)
```
in `R/TMBtools-package.R` should paste this directly into `NAMESPACE`.

**Comment by Craig44** [comment]
So looking at the vignette it looks like the file `✔ Writing 'R/MyTMBPackage-package.R'` is suppose to be written but isn't being created, when I run the function `tmb_create_package.` I am wondering if there is a version mismatch issue?

```
library(TMBtools)
tmb_create_package(path = "PathtotestPkg", tmb_files = c("TMB_files.hpp")))
i Creating package skeleton...
i Copying TMB files...
✔ Creating 'src/'
✔ Creating 'src/TMB/'
✔ Writing 'src/TMB/TMB_files.hpp'
i Adding TMB infrastructure...
✔ Writing 'src/TMB/compile.R'
✔ Writing 'src/Makevars'
✔ Writing 'src/Makevars.win'
i Updating DESCRIPTION...
✔ Writing 'src/init_dummy_file.cpp'
✔ Writing 'NAMESPACE'
✔ Done!
● Add the following line to the NAMESPACE file:

useDynLib(testPkg, .registration=TRUE); useDynLib(testPkg_TMBExports)

● Delete 'src/init_dummy_file.cpp' if C++ files are later added to 'src/'.
> packageVersion("TMBtools")
[1] ‘0.9’
packageVersion("devtools")
[1] ‘2.1.0’
Sys.info()[c("sysname", "release")]
   sysname    release 
 "Windows" ">= 8 x64" 
sessionInfo()$'R.version'$'version.string'
[1] "R version 3.6.1 (2019-07-05)"
> 
```

**Comment by mlysy** [comment]
Thanks for providing these details.  I've pushed a new version of **TMBtools** which works for the latest CRAN releases of **usethis** and **devtools** (latter required to build vignettes).  It seems to pass `devtools::check()` on my local setup (macOS) and `devtools::check_win_devel()` on the CRAN [Windows](https://win-builder.r-project.org/) machines.

Can you please confirm whether your issue still persists?

**Comment by Craig44** [comment]
Thanks for the updates. I can confirm once I updated the R package `devtools` which `usethis` is part of to the following version
```
packageVersion("devtools")
[1] ‘2.3.2’
```
Everything worked as expected.

**Comment by iagomosqueira** [comment]
It seems running the example appears to fail again with the same error when running `devtools::check()`

```
Error (test-gamma_ADFun.R:19:5): gamma_ADFun calculates correct negloglik, gradient, and hessian ──
Error: "getParameterOrder" not available for .Call() for package "TMBExampleTest_TMBExports"
```

on Linux, R 4.0.4, devtools 2.3.2, and usethis 2.0.1.

Same error for a package created using `tmb_create_package`. And the two calls to useDynLib are in the NAMESPACE as expected.

**Comment by mlysy** [comment]
Seems to be because of how devtools loads DLLs when they are compiled in the same session.

The README now specifies that you must quit + restart R between calls to `devtools::document()` and `devtools::check()`.  I've made corresponding changes in the package vignette.

**Comment by iagomosqueira** [comment]
Thanks. `devtools::check` passes now, but after `devtools::load_all()` I still get the same error when running the tests. They work if I install either via `devtools::install` or old-fashioned `R CMD build / INSTALL`. So it seems mostly now a `load_all()` problem, in case you want to warn about it.
